server {
  listen 18311;
  server_name admin.jnotifier.devapps.codingworks.in;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location = /404.html {
    root /usr/share/nginx/html;
  }
}